#src/Resources/config/runner_rabbitmq.yml
parameters:
  teknoo.east.bundle.coderunner.runner.remote_php7.class: 'Teknoo\East\CodeRunner\Runner\RemotePHP7Runner\RemotePHP7Runner'
  teknoo.east.bundle.coderunner.runner.remote_php7.identifier: 'RemotePHP7Runner'
  teknoo.east.bundle.coderunner.runner.remote_php7.name: 'RemotePHP7Runner'
  teknoo.east.bundle.coderunner.runner.remote_php7.version: '0.0.1'

  teknoo.east.bundle.coderunner.worker.rabbit_mq_return_consumer.class: 'Teknoo\East\CodeRunner\Worker\RabbitMQReturnConsumerWorker'

  teknoo.east.bundle.coderunner.listener.amqp_listener.class: 'Teknoo\East\CodeRunnerBundle\Listener\AMQPListener'

services:
  teknoo.east.bundle.coderunner.runner.remote_php7.abstract:
    class: '%teknoo.east.bundle.coderunner.runner.remote_php7.class%'
    private: false
    abstract: true
    arguments:
      - '@teknoo.east.bundle.coderunner.vendor.old_sound_producer.remote_php7.task'
      - '%teknoo.east.bundle.coderunner.runner.remote_php7.identifier%'
      - '%teknoo.east.bundle.coderunner.runner.remote_php7.name%'
      - '%teknoo.east.bundle.coderunner.runner.remote_php7.version%'
      - []
      - '@logger'
    calls:
      - ['addCapability', ['@teknoo.east.bundle.coderunner.runner.capability.language.php7']]

  teknoo.east.bundle.coderunner.worker.rabbit_mq_return_consumer.abstract:
    class: '%teknoo.east.bundle.coderunner.worker.rabbit_mq_return_consumer.class%'
    private: false
    abstract: true
    arguments:
      - '@teknoo.east.bundle.coderunner.registry.tasks'
      - '@teknoo.east.bundle.coderunner.runner.remote_php7'
      - '@teknoo.east.bundle.coderunner.manager.runners'
      - '@logger'

  teknoo.east.bundle.coderunner.listener.amqp_listener:
    class: '%teknoo.east.bundle.coderunner.listener.amqp_listener.class%'
    arguments:
      - 'die'
    tags:
      - { name: 'kernel.event_listener', event: 'after_processing', method: 'onAfterProcessingMessage' }
