registerTask:
    path: '/task/new'
    methods:  ['PUT', 'POST']
    defaults: { _controller: 'teknoo.east.bundle.coderunner.endpoint.register_task' }

deleteTask:
    path: '/task/{taskId}'
    methods:  ['DELETE']
    defaults: { _controller: 'teknoo.east.bundle.coderunner.endpoint.delete_task' }

getTask:
    path: '/task/{taskId}'
    methods:  ['GET']
    defaults: { _controller: 'teknoo.east.bundle.coderunner.endpoint.get_task' }
