#src/Resources/config/services.yml
parameters:
  #Task entity
  teknoo.east.bundle.coderunner.entity.task.class: 'Teknoo\East\CodeRunner\Entity\Task\Task'
  teknoo.east.bundle.coderunner.entity.task_execution.class: 'Teknoo\East\CodeRunner\Entity\TaskExecution'
  teknoo.east.bundle.coderunner.entity.task_registration.class: 'Teknoo\East\CodeRunner\Entity\TaskRegistration'
  teknoo.east.bundle.coderunner.entity.task_standby.class: 'Teknoo\East\CodeRunner\Entity\TaskStandby'

  teknoo.east.bundle.coderunner.entity.task.name: 'TeknooEastCodeRunner:Task\Task'
  teknoo.east.bundle.coderunner.entity.task_execution.name: 'TeknooEastCodeRunner:TaskExecution'
  teknoo.east.bundle.coderunner.entity.task_registration.name: 'TeknooEastCodeRunner:TaskRegistration'
  teknoo.east.bundle.coderunner.entity.task_standby.name: 'TeknooEastCodeRunner:TaskStandby'

  #Repository
  teknoo.east.bundle.coderunner.repository.task.class: 'Teknoo\East\CodeRunner\Repository\TaskRepository'
  teknoo.east.bundle.coderunner.repository.task_execution.class: 'Teknoo\East\CodeRunner\Repository\TaskExecutionRepository'
  teknoo.east.bundle.coderunner.repository.task_registration.class: 'Teknoo\East\CodeRunner\Repository\TaskRegistrationRepository'
  teknoo.east.bundle.coderunner.repository.task_standby.class: 'Teknoo\East\CodeRunner\Repository\TaskStandbyRepository'

  #Manager
  teknoo.east.bundle.coderunner.manager.runners.class: 'Teknoo\East\CodeRunner\Manager\RunnerManager\RunnerManager'
  teknoo.east.bundle.coderunner.manager.tasks.class: 'Teknoo\East\CodeRunner\Manager\TaskManager'
  teknoo.east.bundle.coderunner.manager.tasks.identifier: ''
  teknoo.east.bundle.coderunner.manager.tasks.url: ''

  #Registry
  teknoo.east.bundle.coderunner.registry.tasks_by_runner.class: 'Teknoo\East\CodeRunner\Registry\TasksByRunnerRegistry'
  teknoo.east.bundle.coderunner.registry.tasks_manager_by_task.class: 'Teknoo\East\CodeRunner\Registry\TasksManagerByTasksRegistry'
  teknoo.east.bundle.coderunner.registry.tasks_standby.class: 'Teknoo\East\CodeRunner\Registry\TasksStandbyRegistry'
  teknoo.east.bundle.coderunner.registry.tasks.class: 'Teknoo\East\CodeRunner\Registry\TasksRegistry'

  #Runner
  teknoo.east.bundle.coderunner.runner.capability.class: 'Teknoo\East\CodeRunner\Runner\Capability'

  #Service
  teknoo.east.bundle.coderunner.service.dates.class: 'Teknoo\East\CodeRunner\Service\DatesService'

  #Endpoinds
  teknoo.east.bundle.coderunner.endpoint.delete_task.class: 'Teknoo\East\CodeRunner\EndPoint\DeleteTaskEndPoint'
  teknoo.east.bundle.coderunner.endpoint.get_task.class: 'Teknoo\East\CodeRunner\EndPoint\GetTaskEndPoint'
  teknoo.east.bundle.coderunner.endpoint.register_task.class: 'Teknoo\East\CodeRunner\EndPoint\RegisterTaskEndPoint'
  teknoo.east.bundle.coderunner.endpoint.load_next_tasks.class: 'Teknoo\East\CodeRunner\EndPoint\LoadNextTasksEndPoint'

services:
  #Repository
  teknoo.east.bundle.coderunner.repository.task:
    class: '%teknoo.east.bundle.coderunner.repository.task.class%'
    factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
    arguments: ['%teknoo.east.bundle.coderunner.entity.task.name%']
    private: true

  teknoo.east.bundle.coderunner.repository.task_execution:
    class: '%teknoo.east.bundle.coderunner.repository.task_execution.class%'
    factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
    arguments: ['%teknoo.east.bundle.coderunner.entity.task_execution.name%']
    private: true

  teknoo.east.bundle.coderunner.repository.task_registration:
    class: '%teknoo.east.bundle.coderunner.repository.task_registration.class%'
    factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
    arguments: ['%teknoo.east.bundle.coderunner.entity.task_registration.name%']
    private: true

  teknoo.east.bundle.coderunner.repository.task_standby:
    class: '%teknoo.east.bundle.coderunner.repository.task_standby.class%'
    factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
    arguments: ['%teknoo.east.bundle.coderunner.entity.task_standby.name%']
    private: true

  #Registry
  teknoo.east.bundle.coderunner.registry.tasks_by_runner:
    class: '%teknoo.east.bundle.coderunner.registry.tasks_by_runner.class%'
    arguments:
      - '@teknoo.east.bundle.coderunner.service.dates'
      - '@teknoo.east.bundle.coderunner.repository.task_execution'
      - '@doctrine.orm.entity_manager'
    private: true

  teknoo.east.bundle.coderunner.registry.tasks_manager_by_task:
    class: '%teknoo.east.bundle.coderunner.registry.tasks_manager_by_task.class%'
    arguments:
      - '@teknoo.east.bundle.coderunner.service.dates'
      - '@teknoo.east.bundle.coderunner.repository.task_registration'
      - '@doctrine.orm.entity_manager'
    private: true

  teknoo.east.bundle.coderunner.registry.tasks_standby:
    class: '%teknoo.east.bundle.coderunner.registry.tasks_standby.class%'
    arguments:
      - '@teknoo.east.bundle.coderunner.service.dates'
      - '@teknoo.east.bundle.coderunner.repository.task_standby'
      - '@doctrine.orm.entity_manager'
    private: true

  teknoo.east.bundle.coderunner.registry.tasks:
    class: '%teknoo.east.bundle.coderunner.registry.tasks.class%'
    arguments:
      - '@teknoo.east.bundle.coderunner.repository.task'

  #Runner
  teknoo.east.bundle.coderunner.runner.capability.language.php7:
    class: '%teknoo.east.bundle.coderunner.runner.capability.class%'
    arguments: ['php', '>=7']
    private: true
    shared: false

  #Manager
  teknoo.east.bundle.coderunner.manager.runners:
    class: '%teknoo.east.bundle.coderunner.manager.runners.class%'
    private: false
    arguments:
      - '@teknoo.east.bundle.coderunner.registry.tasks_by_runner'
      - '@teknoo.east.bundle.coderunner.registry.tasks_manager_by_task'
      - '@teknoo.east.bundle.coderunner.registry.tasks_standby'

  teknoo.east.bundle.coderunner.manager.tasks.abstract:
    class: '%teknoo.east.bundle.coderunner.manager.tasks.class%'
    private: false
    abstract: true
    arguments:
      - '%teknoo.east.bundle.coderunner.manager.tasks.identifier%'
      - '%teknoo.east.bundle.coderunner.manager.tasks.url%'
      - '@doctrine.orm.entity_manager'
      - '@teknoo.east.bundle.coderunner.service.dates'

  #Service
  teknoo.east.bundle.coderunner.service.dates:
    class: '%teknoo.east.bundle.coderunner.service.dates.class%'
    private: true

  #Controller endpoint
  teknoo.east.bundle.coderunner.endpoint.delete_task:
    class: '%teknoo.east.bundle.coderunner.endpoint.delete_task.class%'
    arguments:
      - '@teknoo.east.bundle.coderunner.registry.tasks_manager_by_task'
      - '@teknoo.east.bundle.coderunner.registry.tasks'
    tags:
      - {name: 'east.controller.service'}

  teknoo.east.bundle.coderunner.endpoint.get_task:
    class: '%teknoo.east.bundle.coderunner.endpoint.get_task.class%'
    arguments:
      - '@teknoo.east.bundle.coderunner.registry.tasks'
    tags:
      - {name: 'east.controller.service'}

  teknoo.east.bundle.coderunner.endpoint.register_task:
    class: '%teknoo.east.bundle.coderunner.endpoint.register_task.class%'
    arguments:
      - '@teknoo.east.bundle.coderunner.manager.runners'
    tags:
      - {name: 'east.controller.service'}

  teknoo.east.bundle.coderunner.endpoint.load_next_tasks:
    class: '%teknoo.east.bundle.coderunner.endpoint.load_next_tasks.class%'
    arguments:
      - '@teknoo.east.bundle.coderunner.manager.runners'
    tags:
      - {name: 'east.controller.service'}
