#src/Resources/config/services.yml
parameters:
  #Task entity
  teknoo.east.bundle.coderunner.entity.task.class: 'Teknoo\East\CodeRunnerBundle\Entity\Task\Task'
  teknoo.east.bundle.coderunner.entity.task_execution.class: 'Teknoo\East\CodeRunnerBundle\Entity\TaskExecution'
  teknoo.east.bundle.coderunner.entity.task_registration.class: 'Teknoo\East\CodeRunnerBundle\Entity\TaskRegistration'

  teknoo.east.bundle.coderunner.entity.task.name: 'TeknooEastCodeRunnerBundle:Task'
  teknoo.east.bundle.coderunner.entity.task_execution.name: 'TeknooEastCodeRunnerBundle:TaskExecution'
  teknoo.east.bundle.coderunner.entity.task_registration.name: 'TeknooEastCodeRunnerBundle:TaskRegistration'

  #Repository
  teknoo.east.bundle.coderunner.repository.task.class: 'Teknoo\East\CodeRunnerBundle\Repository\TaskRepository'
  teknoo.east.bundle.coderunner.repository.task_execution.class: 'Teknoo\East\CodeRunnerBundle\Repository\TaskExecutionRepository'
  teknoo.east.bundle.coderunner.repository.task_registration.class: 'Teknoo\East\CodeRunnerBundle\Repository\TaskRegistrationRepository'

  #Manager
  teknoo.east.bundle.coderunner.manager.runners.class: 'Teknoo\East\CodeRunnerBundle\Manager\RunnerManager\RunnerManager'
  teknoo.east.bundle.coderunner.manager.tasks.class: 'Teknoo\East\CodeRunnerBundle\Manager\TaskManager\TaskManager'

  #Registry
  teknoo.east.bundle.coderunner.registry.tasks_by_runner.class: 'Teknoo\East\CodeRunnerBundle\Registry\TasksByRunnerRegistry'
  teknoo.east.bundle.coderunner.registry.tasks_manager_by_task.class: 'Teknoo\East\CodeRunnerBundle\Registry\TasksManagerByTasksRegistry'

  #Runner
  teknoo.east.bundle.coderunner.runner.remote_docker_php7.class: 'Teknoo\East\CodeRunnerBundle\Runner\RemoteDockerPHP7Runner\RemoteDockerPHP7Runner'
  teknoo.east.bundle.coderunner.runner.capability.class: 'Teknoo\East\CodeRunnerBundle\Runner\Capability'

  #Service
  teknoo.east.bundle.coderunner.service.dates.class: 'Teknoo\East\CodeRunnerBundle\Service\DatesService'

services:
  #Repository
  teknoo.east.bundle.coderunner.repository.task:
    class: '%teknoo.east.bundle.coderunner.repository.task%'
    factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
    arguments: ['%teknoo.east.bundle.coderunner.entity.task.name%']
    private: true

  teknoo.east.bundle.coderunner.repository.task_execution:
    class: '%teknoo.east.bundle.coderunner.repository.task_execution%'
    factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
    arguments: ['%teknoo.east.bundle.coderunner.entity.task_execution.name%']
    private: true

  teknoo.east.bundle.coderunner.repository.task_registration:
    class: '%teknoo.east.bundle.coderunner.repository.task_registration%'
    factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
    arguments: ['%teknoo.east.bundle.coderunner.entity.task_registration.name%']
    private: true

  #Registry
  teknoo.east.bundle.coderunner.registry.tasks_by_runner:
    class: '%teknoo.east.bundle.coderunner.registry.tasks_by_runner.class%'
    arguments:
      - '@teknoo.east.bundle.coderunner.service.dates'
      - '@teknoo.east.bundle.coderunner.repository.task_execution'
      - '@doctrine.orm.entity_manager'
    private: true

  teknoo.east.bundle.coderunner.registry.tasks_manager_by_task:
    class: '%teknoo.east.bundle.coderunner.registry.tasks_manager_by_task.class%'
    arguments:
      - '@teknoo.east.bundle.coderunner.service.dates'
      - '@teknoo.east.bundle.coderunner.repository.task_registration'
      - '@doctrine.orm.entity_manager'
    private: true

  #Runner
  teknoo.east.bundle.coderunner.runner.capability.language.php7:
    class: '%teknoo.east.bundle.coderunner.runner.capability.class%'
    argument: ['language', 'php7']
    private: true
    shared: false

  teknoo.east.bundle.coderunner.runner.capability.feature.composer:
    class: '%teknoo.east.bundle.coderunner.runner.capability.class%'
    argument: ['feature', 'composer']
    private: true
    shared: false

  teknoo.east.bundle.coderunner.runner.capability.feature.curl:
    class: '%teknoo.east.bundle.coderunner.runner.capability.class%'
    argument: ['feature', 'curl']
    private: true
    shared: false

  teknoo.east.bundle.coderunner.runner.capability.feature.zip:
    class: '%teknoo.east.bundle.coderunner.runner.capability.class%'
    argument: ['feature', 'zip']
    private: true
    shared: false

  teknoo.east.bundle.coderunner.runner.remote_docker_php7:
    class: '%teknoo.east.bundle.coderunner.runner.remote_docker_php7.class%'
    private: false
    calls:
      - ['addCapability', ['@teknoo.east.bundle.coderunner.runner.capability.language.php7']]
      - ['addCapability', ['@teknoo.east.bundle.coderunner.runner.capability.language.composer']]
      - ['addCapability', ['@teknoo.east.bundle.coderunner.runner.capability.language.curl']]
      - ['addCapability', ['@teknoo.east.bundle.coderunner.runner.capability.language.zip']]
    tags:
      - {name: 'teknoo.east.coderunner.runner'}

  #Manager
  teknoo.east.bundle.coderunner.manager.runners:
    class: '%teknoo.east.bundle.coderunner.manager.runners.class%'
    private: false
    arguments:
      - '@teknoo.east.bundle.coderunner.registry.tasks_by_runner'
      - '@teknoo.east.bundle.coderunner.registry.tasks_manager_by_task'

  teknoo.east.bundle.coderunner.manager.tasks:
    class: '%teknoo.east.bundle.coderunner.manager.tasks%'
    private: false
    tags:
          - {name: 'teknoo.east.coderunner.task_manager'}

  #Service
  teknoo.east.bundle.coderunner.service.dates:
    class: '%teknoo.east.bundle.coderunner.service.dates.class%'
    private: false