#src/Resources/config/doctrine/task_registration.orm.yml
Teknoo\East\CodeRunner\Entity\TaskRegistration:
  type: 'entity'
  table: 'task_registration'
  repositoryClass: 'Teknoo\East\CodeRunner\Repository\TaskRegistrationRepository'
  id:
    id:
      type: 'integer'
      generator: { strategy: 'AUTO' }
  gedmo:
    soft_deleteable:
      field_name: 'deletedAt'
      time_aware: false
  fields:
    taskManagerIdentifier:
      type: 'string'
      column: 'task_manager_identifier'
      length: 100
    createdAt:
      type: 'datetime'
      column: 'created_at'
      gedmo:
        timestampable:
          on: 'create'
    updatedAt:
      type: 'datetime'
      column: 'updated_at'
      gedmo:
        timestampable:
          on: 'update'
    deletedAt:
      type: 'datetime'
      column: 'deleted_at'
      nullable: true
  manyToOne:
    task:
      targetEntity: 'Teknoo\East\CodeRunner\Entity\Task\Task'
      joinColumn:
        name: 'task_id'
        referencedColumnName: 'id'
