#src/Resources/config/doctrine/Task.orm.yml
Teknoo\East\CodeRunner\Entity\Task\Task:
  type: 'entity'
  table: 'task'
  repositoryClass: 'Teknoo\East\CodeRunner\Repository\TaskRepository'
  id:
    id:
      type: 'guid'
      generator: { strategy: 'UUID' }
  gedmo:
    soft_deleteable:
      field_name: 'deletedAt'
      time_aware: false
  fields:
    code:
      type: 'text'
      nullable: true
    url:
      type: 'string'
      length: 500
      nullable: true
    status:
      type: 'text'
      nullable: true
    result:
      type: 'text'
      nullable: true
    createdAt:
      type: 'datetime'
      column: 'created_at'
      gedmo:
        timestampable:
          on: 'create'
    updatedAt:
      type: 'datetime'
      column: 'updated_at'
      gedmo:
        timestampable:
          on: 'update'
    deletedAt:
      type: 'datetime'
      column: 'deleted_at'
      nullable: true
  lifecycleCallbacks:
    postLoad: [ 'postLoadJsonUpdate' ]
    prePersist: [ 'prePersistJsonUpdate' ]
    preFlush: [ 'prePersistJsonUpdate' ]
