Teknoo\East\CodeRunnerBundle\Entity\TaskExecution:
type: 'entity'
  table: 'task_execution'
  repositoryClass: 'Teknoo\East\CodeRunnerBundle\Repository\TaskExecutionRepository'
  id:
    id:
      type: 'integer'
      generator: { strategy: 'AUTO' }
  gedmo:
    soft_deleteable:
      field_name: 'deletedAt'
      time_aware: false
  fields:
    code:
      type: 'json'
    createdAt:
      type: 'datetime'
      gedmo:
        timestampable:
          on: 'create'
    updatedAt:
      type: 'datetime'
      gedmo:
        timestampable:
          on: 'update'
    deletedAt:
      type: 'date'
        nullable: true